### ISSUE TITLE
Twitter運用

### ISSUE THREAD

**Issue by tomihe0720** [moreserita/marketing#5]

**Comment by tomihe0720** [comment]
[https://twitter.com/wave_moreinvest](url)
### **目的**：
「利用前ユーザーとの接点」
「ブランド作り」⇒【オシャレ】【学生】【関西】

**Comment by tomiheeee** [comment]
## **数**

- [ ] １ツイート/日

はノルマに

**Comment by tomiheeee** [comment]
github使い方難しいです。

**Comment by tomihe0720** [comment]
## エンゲージメント指標

- フォロワー数


- いいね獲得数

 

- リツイート数

- インプレッション割合

**Comment by tomihe0720** [comment]
### 重点指標

- フォロワー数
認知拡大、 

- いいね獲得数
ブランド構築、

## ＜分析＞
週に2回、振り返り
**日曜**と**木曜**に行う。（オンラインMTG日）

**Comment by tomihe0720** [comment]
### ＜週間目標＞1/23~/29

### - フォロワー数　100

- [ ] フォロー数　250

- [ ] 投稿数　10

- [ ] インプレッション率30%　（画像付き投稿を基本に）

**Comment by tomiheeee** [comment]
## ターゲットとするフォロワー層

学生のフォロワー多い学生
学生団体アカウント
大学教授

**Comment by tomihe0720** [comment]
【メモ】企業アカウントのフォローの仕方
ｂｙせりた
シェアされてるアカウント
イベントまとめ情報流してくれる
オシャレな写真をのせてる（デザイン系関心から）

**Comment by tomihe0720** [comment]
1/29　振り返り
＜週間目標＞1/23~/29

## - [ ] フォロワー数　100

**54**　×　
半分ほどしかいってない、かつほとんどアイセッカー
→フォロワー層狙ってツイートも考えていく（阪大学生団体→そこのフォロワー→一般学生）

 

## - [ ] フォロー数　250

**106**　×
フォロワー数が伸びてこないのでなかなかフォローしづらい
→フォロバを期待できる学生団体からのフォローを優先で

１日１ツイートが最低ノルマ+リツイート積極的に

##  - [ ]  投稿数　10

 インプレッション率30%　（画像付き投稿を基本に）

**8**

※インプレッション率いまだ表示されず

**Comment by tomihe0720** [comment]
### ＜週間目標＞1/30～2/2

### - フォロワー数　100

- [ ] フォロー数　200

- [ ] 投稿数　20（累計）

**Comment by tomihe0720** [comment]
### ＜振り返り＞2/5

- [ ]  フォロワー数　100
 ## 94 
1週間で30ちょいしか伸びてない、、
フォローに対するリフォローがほとんどありません。
ツイートが影響？？、、

- [ ] フォロー数　200
## 90
これは、じゅんちゃんからの指摘通りFF比を気にして、削減した。
フォロー数は指標から外すべきかな。

- [ ] 投稿数　20（累計）
## 14
これも指摘通り、阪大系のツイートを削除したために、ツイート数が減ってしまった。
しかし、一日2ツイートぐらいはしたい

**Comment by tomihe0720** [comment]
### ＜週間目標＞2/6～2/9


- [ ]  フォロワー数　150


- [ ] 投稿数　22（累計）


※ターゲット修正↓

【Twitter運営の目的】
①活動認知 ②市場認識③イベント参加促進

【ターゲットの設定】
○意識層について
意識高くない層も含めた大学生
↓
学生団体（社会活動系、趣味系、スポーツ系なんでもOK）に所属する学生がメインターゲット
※既に意識高く、参加してる層はイベント、イベント管理サービスの認知はある

○大学について
梅田でのイベントに参加でき、一定数の意識高い大学生がいる大学
↓
関関同立、京阪神
ここからは絞らない

**Comment by tomihe0720** [comment]
2/22
### 【Twitter運営目的確認】

①認知拡大　②学生団体囲い込み
↓
1.フォロワー数の拡大
2.学生団体アカウントの徹底フォロー、リスト作成

**Comment by tomihe0720** [comment]
2/22【現状確認】
フォロー数　　124
フォロワー数　167
ツイート数　　27

### やったこと

- 相互フォローアカウント利用

アカウントフォロー直後はフォロー伸びる。
→**一定期間置いてリムる→再フォロー**

- 学生団体が追加されているリスト確認

一番学生団体をたどるのに効率よい。

### 【課題】

- 単純に1人での更新しんどい→週1でのネタため、予約投稿機能使う、ひろとへの協力依頼

- 画像不足→ヒロトとの定期MTG

- 「学生イベントに興味ない」の声多数。→ある程度、軸を外しながらのおもろいアカウント作り。

- 「運営母体が見えない」の声→メンバー紹介のやり方を模索中。次回のSNSえむで決めたい

**Comment by tomihe0720** [comment]
3/13【現状確認】
フォロー数　　107
フォロワー数　235
ツイート数　　37

やったこと

- Wantedlyの利用
Wantedlyで学生マーケターとエンジニア募集と掲げて、意識高い学生からのフォロー、コンタクトを狙う
→徐々に連絡がなくなっている、繰り返して更新する

- メンバーの写真の積極的投稿
メンバー紹介、活動の様子の写真を投稿して、ビジネスアカウント臭さを消す。学生でやってる感を全面に出す。DMが飛んできたり、学生運営であることの認知は上がってきている。

- イベント紹介
ドリプラ大阪のイベントの紹介ツイートをしたが、反応なし。
→前もって、向こうの担当者にリツイートなどの依頼は必要

【課題】

- 単純に1人での更新しんどい→週1でのネタため、予約投稿機能使う、ひろとへの協力依頼

- ベータ版がWebサービス⇒スマホアプリへ移行？
→ミーティングで今後の投稿の方向修正(スマホの画像利用、"アプリ"のワード使うのか)

- A/Bテストの実施
→週末に実験テーマ決めて、1週間の投稿スタンスを決めておく。

- フォロワー数
→特定ユーザー狙ったツイート⇒フォローの作業
→新入生狙った投稿
