### ISSUE TITLE
各大学ごとイベントDB作成

### ISSUE THREAD

**Issue by tomihe0720** [moreserita/marketing#6]
学生イベントの主催者が属する大学によって分類する。

DB作成順（予定）
大阪大学
↓
京都大学
↓
関西大学
↓
以下未定

**Comment by moreserita** [comment]
**２月２０日まで！！締め切り**

京阪神関関同立＋芸大＋エンジニア系（connpassで）

各大学のイベント名
主催者（団体）
イベントジャンル
URL

**Comment by moreserita** [comment]
これどうなってる？
